#:kivy 2.2.1
MDScreenManager
    id: "screenManager"
    name: "screenManager"
    MDScreen:
        name: "homeScreen"
        AnchorLayout:
            anchor_x: 'center'
            anchor_y: 'top'
            orientation: 'vertical'
            MDTopAppBar:
                title: "Tasks"
                anchor_title: "left"
                right_action_items: [["plus", lambda x: app.callback(x), "Add task"]]
                elevation: 10
    MDScreen: 
        name: "addTaskScreen"